Accounting::Asset.create(code: 10101010, name: 'Cash - Local Treasury')
Accounting::Asset.create(code: 10301010, name: 'Accounts Receivable')
Accounting::Revenue.create(code: 40101020, name: 'Professional Tax')
Accounting::Revenue.create(code: 40101050, name: 'Community Tax')
Accounting::Revenue.create(code: 40101051, name: 'Community Tax - Individual')
Accounting::Revenue.create(code: 40101052, name: 'Community Tax - Corporation')
Accounting::Revenue.create(code: 40102040, name: 'Real Property Tax - Basic')
Accounting::Revenue.create(code: 40102041, name: 'Real Property Tax Land')
Accounting::Revenue.create(code: 40102042, name: 'Real Property Tax Building')
Accounting::Revenue.create(code: 40102043, name: 'Real Property Tax Machinery')
Accounting::Revenue.create(code: 40102041, name: 'Discount on Real Property Tax-Basic', contra: true)
Accounting::Revenue.create(code: 40102050, name: 'Special Education Tax')
Accounting::Revenue.create(code: 40102051, name: 'Discount on Special Education Tax')
Accounting::Revenue.create(code: 40102060, name: 'Special Levy on Idle Lands')
Accounting::Revenue.create(code: 40102070, name: 'Special Levy on Lands Benefited for Public Works Projects')
Accounting::Revenue.create(code: 40102080, name: 'Real Property Transfer Tax')
Accounting::Revenue.create(code: 40103030, name: 'Business Tax')
Accounting::Revenue.create(code: 40104999, name: 'Capital Tax')
Accounting::Revenue.create(code: 40103031, name: 'Business Tax - Manufacturers, assemblers, etc.')
Accounting::Revenue.create(code: 40103032, name: 'Business Tax - Wholesalers, distributors, etc.')
Accounting::Revenue.create(code: 40103033, name: 'Business Tax - Exporters, etc.')
Accounting::Revenue.create(code: 40103034, name: 'Business Tax - Retailers')
Accounting::Revenue.create(code: 40103035, name: 'Business Tax - Contractors and Independent Contractors')
Accounting::Revenue.create(code: 40103036, name: 'Business Tax - Banks and Other Financial Institutions')
Accounting::Revenue.create(code: 40103037, name: 'Business Tax - Peddlers')
Accounting::Revenue.create(code: 40103038, name: 'Business Tax - Businesses consisting essentially of sales of services')
Accounting::Revenue.create(code: 40103039, name: 'Business Tax - Mobile Traders')
Accounting::Revenue.create(code: 40103099, name: 'Business Tax - Other Businesses')
Accounting::Revenue.create(code: 40103040, name: 'Tax on Sand, Gravel and Other Quarry Products')
Accounting::Revenue.create(code: 40103050, name: 'Tax on Delivery Trucks and Vans')
Accounting::Revenue.create(code: 40103060, name: 'Amusement Tax')
Accounting::Revenue.create(code: 40103070, name: 'Franchise Tax')
Accounting::Revenue.create(code: 40103080, name: 'Printing and Publication Tax')
Accounting::Revenue.create(code: 40104990, name: 'Other Taxes')
Accounting::Revenue.create(code: 40105010, name: 'Tax Revenue - Fines and Penalties - Taxes on Individual and Corporation')
Accounting::Revenue.create(code: 40105020, name: 'Tax Revenue - Fines and Penalties - Property Taxes')
Accounting::Revenue.create(code: 40105021, name: 'Real Property Tax Basic Land - Penalty')
Accounting::Revenue.create(code: 40105022, name: 'Real Property Tax Basic Building - Penalty')
Accounting::Revenue.create(code: 40105023, name: 'Real Property Tax Basic Machinery - Penalty')
Accounting::Revenue.create(code: 40105023, name: 'Special Education  Tax - Penalty')
Accounting::Revenue.create(code: 40105030, name: 'Tax Revenue - Fines and Penalties - Taxes on Goods and Services')
Accounting::Revenue.create(code: 40105040, name: 'Tax Revenue - Fines and Penalties - Other Taxes')
Accounting::Revenue.create(code: 40106010, name: 'Share from Internal Revenue Collections')
Accounting::Revenue.create(code: 40106020, name: 'Share from Expanded Value Added Tax')
Accounting::Revenue.create(code: 40106030, name: 'Share from National Wealth')
Accounting::Revenue.create(code: 40106031, name: 'Share from Mining Taxes')
Accounting::Revenue.create(code: 40106032, name: 'Share from Royalty Fees')
Accounting::Revenue.create(code: 40106033, name: 'Share from Proceeds Derived from Hydro-Power Plants, Geothermal and Other Sources of Energy')
Accounting::Revenue.create(code: 40106034, name: 'Share from Forestry and Fishery Charges')
Accounting::Revenue.create(code: 40106040, name: 'Share from Tobacco Excise Tax')
Accounting::Revenue.create(code: 40106050, name: 'Share from Economic Zones')
Accounting::Revenue.create(code: 40201010, name: 'Permit Fees')
Accounting::Revenue.create(code: 402010105, name: 'Business Permit Fees')
Accounting::Revenue.create(code: 402010106, name: 'Building Permit Fees')
Accounting::Revenue.create(code: 402010107, name: "Zonal/Location Permit Fees")
Accounting::Revenue.create(code: 402010108, name: "Trycycle Operators Permit Fee")
Accounting::Revenue.create(code: 402010109, name: "Fishery Rental Fees and Privilege Fees")
Accounting::Revenue.create(code: 402010110, name: "Fees on Weights and Measures")
Accounting::Revenue.create(code: 402010111, name: "Other Permits and Licenses")
Accounting::Revenue.create(code: 40201020, name: "Registration Fees")
Accounting::Revenue.create(code: 402010201, name: "Civil Registration Fees")
Accounting::Revenue.create(code: 402010202, name: "Cattle/Animal Registration Fees")
Accounting::Revenue.create(code: 40201030, name: "Registration Plates, Tags and Stickers Fees")
Accounting::Revenue.create(code: 402010301, name: "Business TIN Plate Fees")
Accounting::Revenue.create(code: 402010302, name: "Sticker Fees")
Accounting::Revenue.create(code: 40201040, name: "Clearance and Certification Fees")
Accounting::Revenue.create(code: 402010402, name: "Secretary's Fees")
Accounting::Revenue.create(code: 402010403, name: "Other Clearance and Certification")
Accounting::Revenue.create(code: 402010404, name: "Health Certificate")
Accounting::Revenue.create(code: 402010405, name: "Other Clearance and Certification")
Accounting::Revenue.create(code: 40201070, name: "Supervision and Regulation Enforcement Fees")
Accounting::Revenue.create(code: 40201100, name: "Inspection Fees")
Accounting::Revenue.create(code: 402011001, name: "Health Inspection Fees")
Accounting::Revenue.create(code: 402011002, name: "Sanitary Inspection Fees")
Accounting::Revenue.create(code: 402011003, name: "Mechanical Inspection Fees")
Accounting::Revenue.create(code: 40201110, name: "Verification and Authentication Fees")
Accounting::Revenue.create(code: 40201130, name: "Processing Fees")
Accounting::Revenue.create(code: 40201140, name: "Occupation Fees")
Accounting::Revenue.create(code: 40201150, name: "Fishery Rentals, Fees and Charges")
Accounting::Revenue.create(code: 40201160, name: "Fees for Sealing and Licensing of Weights and Measures")
Accounting::Revenue.create(code: 40201980, name: "Fines and Penalties - Service Income")
Accounting::Revenue.create(code: 40201990, name: "Other Service Income")
Accounting::Revenue.create(code: 40202010, name: "School Fees")
Accounting::Revenue.create(code: 40202020, name: "Affiliation Fees")
Accounting::Revenue.create(code: 40202040, name: "Seminar/Training Fees")
Accounting::Revenue.create(code: 40202050, name: "Rent Income")
Accounting::Revenue.create(code: 40202060, name: "Communication Network Fees")
Accounting::Revenue.create(code: 40202070, name: "Transportation System Fees")
Accounting::Revenue.create(code: 40202080, name: "Road Network Fees")
Accounting::Revenue.create(code: 40202090, name: "Waterworks System Fees")
Accounting::Revenue.create(code: 402020100, name: "Power Supply System Fees")
Accounting::Revenue.create(code: 402020110, name: "Seaport System Fees")
Accounting::Revenue.create(code: 402020120, name: "Parking Fees")
Accounting::Revenue.create(code: 402020130, name: "Receipts from Operation of Hostels/Dormitories and Other Like Facilities")
Accounting::Revenue.create(code: 402020140, name: "Receipts from Market Operation")
Accounting::Revenue.create(code: 402020150, name: "Receipts from Slaughterhouse Operation")
Accounting::Revenue.create(code: 402020160, name: "Receipts from Cemetery Operation")
Accounting::Revenue.create(code: 402020160, name: "Receipts from Printing and Publication")
Accounting::Revenue.create(code: 402020180, name: "Sales Revenue")
Accounting::Revenue.create(code: 402020181, name: "Sales Discounts", contra: true)
Accounting::Revenue.create(code: 402020190, name: "Garbage Fees")
Accounting::Revenue.create(code: 402020200, name: "Hospital Fees")
Accounting::Revenue.create(code: 402020210, name: "Dividend Income")
Accounting::Revenue.create(code: 402020220, name: "Interest Income")
Accounting::Revenue.create(code: 402020230, name: "Service Concession Revenue")
Accounting::Revenue.create(code: 402020240, name: "Other Service Concession Revenue")
Accounting::Revenue.create(code: 402020250, name: "Lease Revenue")
Accounting::Revenue.create(code: 402020260, name: "Share in the Profit from Joint Venture")
Accounting::Revenue.create(code: 402020980, name: "Fines and Penalties - Business Income")
Accounting::Revenue.create(code: 402020990, name: "Other Business Income")
Accounting::Revenue.create(code: 40301010, name: "Subsidy from National Government")
Accounting::Revenue.create(code: 40301020, name: "Subsidy from Local Government Units")
Accounting::Revenue.create(code: 40301030, name: "Subsidy from Government-Owned and/or Controlled Corporations (GOCCs)")
Accounting::Revenue.create(code: 40301040, name: "Subsidy from Other Funds")
Accounting::Revenue.create(code: 40301050, name: "Subsidy from General Fund Proper /Other Special Accounts")
Accounting::Revenue.create(code: 40301060, name: "Subsidy from Local Economic Enterprises")
Accounting::Revenue.create(code: 40302010, name: "Transfers from General Fund of LGU Counterpart/Equity Share")
Accounting::Revenue.create(code: 40302020, name: "Transfers from General Fund of Unspent DRRMF")
Accounting::Revenue.create(code: 40401010, name: "Share from Philippine amusement and Gaming Corporation (PAGCOR)")
Accounting::Revenue.create(code: 40401020, name: "Share from Philippine Charity Sweepstakes Office (PCSO)")
Accounting::Revenue.create(code: 40402010, name: "Grants and Donations in Cash")
Accounting::Revenue.create(code: 40402020, name: "Grants and Donations in Kind")
Accounting::Revenue.create(code: 40402030, name: "Grants from concessionary Loan")
Accounting::Revenue.create(code: 40501010, name: "Gain from Changes in Fair Value of Financial Instruments")
Accounting::Revenue.create(code: 40501020, name: "Gain on Foreign Exchange (FOREX)")
Accounting::Revenue.create(code: 40501030, name: "Gain on Sale of Investments")
Accounting::Revenue.create(code: 40501040, name: "Gain on Sale of Investment Property")
Accounting::Revenue.create(code: 40501050, name: "Gain on Sale of Property, Plant and Equipment")
Accounting::Revenue.create(code: 40501060, name: "Gain on Initial Recognition of Biological Assets")
Accounting::Revenue.create(code: 40501070, name: "Gain on Sale of Biological Assets")
Accounting::Revenue.create(code: 40501080, name: "Gain from Changes in Fair Value Less Cost to Sell of Biological Assets Due to Physical Change")
Accounting::Revenue.create(code: 40501090, name: "Gain from Changes in Fair Value Less Cost to Sell of Biological Assets Due to Price Change")
Accounting::Revenue.create(code: 405010100, name: "Gain from Initial Recognition of Agricultural Produce")
Accounting::Revenue.create(code: 405010110, name: "Gain on Sale of Intangible Assets")
Accounting::Revenue.create(code: 405010120, name: "Reversal of Impairment Losses")
Accounting::Revenue.create(code: 40501990, name: "Other Gains")
Accounting::Revenue.create(code: 40601010, name: "Miscellaneous Income")
Accounting::Revenue.create(code: 40701010, name: "Sale of Garnished/Confiscated/Abandoned Goods and Properties")
